server:
  port: 8082

spring:

  application:
    name: billings-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/billings
    username: postgres
    password: simple123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true